name: Deploy to Discord webhook

on:
  # push:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  create-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3